version: '3.8'

services:
  api:
    build: .
    container_name: restall-api
    environment:
      - DB_URL=jdbc:postgresql://db:5432/restall
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - JWT_SECRET=${JWT_SECRET}
      - SENDGRID=${SENDGRID}
      - SENDGRID_EMAIL=${SENDGRID_EMAIL}
      - SERVER_FORWARD_HEADERS_STRATEGY=framework
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env

  caddy:
    image: caddy:2.7.5-alpine
    container_name: caddy-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api

  db:
    image: postgres:15-alpine
    container_name: restall-db
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: restall
    ports:
      - "5433:5432"
    volumes:
      - restall-pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  restall-pgdata:
  caddy_data:
  caddy_config:
