CREATE TABLE estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_produto VARCHAR(255) NOT NULL,
    quantidade INTEGER NOT NULL,
    preco_unitario NUMERIC(10, 2) NOT NULL,
    unidade_medida VARCHAR(50) NOT NULL,
    data_validade DATE,
    restaurante_id BIGINT NOT NULL,
    criado_em TIMESTAMP(6) NOT NULL,
    atualizado_em TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_estoque_restaurante FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
);
