CREATE TABLE despesas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(255) NOT NULL,
    valor NUMERIC(10, 2) NOT NULL,
    data_despesa TIMESTAMP(6) NOT NULL,
    categoria VARCHAR(100) NOT NULL,
    restaurante_id BIGINT NOT NULL,
    criado_em TIMESTAMP(6) NOT NULL,
    atualizado_em TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_despesa_restaurante FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
);
