CREATE TABLE comandas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero INTEGER NOT NULL,
    mesa INTEGER NOT NULL,
    funcionario_id BIGINT NOT NULL,
    restaurante_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    valor_total NUMERIC(10, 2) DEFAULT 0.0,
    data_abertura TIMESTAMP(6) NOT NULL,
    data_fechamento TIMESTAMP(6),
    criado_em TIMESTAMP(6) NOT NULL,
    atualizado_em TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_comanda_funcionario FOREIGN KEY (funcionario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_comanda_restaurante FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id)
);

CREATE TABLE pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comanda_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    quantidade INTEGER NOT NULL,
    observacao VARCHAR(255),
    status VARCHAR(50) NOT NULL,
    preco_unitario NUMERIC(10, 2) NOT NULL,
    valor_total NUMERIC(10, 2) NOT NULL,
    data_pedido TIMESTAMP(6) NOT NULL,
    criado_em TIMESTAMP(6) NOT NULL,
    atualizado_em TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_pedido_comanda FOREIGN KEY (comanda_id) REFERENCES comandas(id),
    CONSTRAINT fk_pedido_item FOREIGN KEY (item_id) REFERENCES itens_cardapio(id)
);
